// ── Supported objects per connector ──────────────────────────────────────────

export interface ConnectorObjectDef {
  id: string;
  name: string;
  description: string;
  rowCount: number;
  syncMode: "full_refresh" | "incremental";
  recommended?: boolean;
}

export type ConnectorCategory =
  | "ecommerce"
  | "payments"
  | "marketing"
  | "crm"
  | "support"
  | "database"
  | "warehouse"
  | "storage"
  | "productivity"
  | "devtools"
  | "analytics";

export type ConnectorStatus = "connected" | "available" | "beta" | "coming_soon";
export type ConnectorHealth = "healthy" | "degraded" | "error" | "idle" | null;

export interface ConnectorDef {
  id: string;
  name: string;
  slug: string;
  category: ConnectorCategory;
  description: string;
  color: string;           // brand background color
  textColor?: string;      // text on the logo badge (default white)
  abbr: string;            // 2–3 char abbreviation for logo
  status: ConnectorStatus;
  health: ConnectorHealth;
  lastSync: string | null;
  nextSync: string | null;
  syncFrequency: string;
  totalRecords: number;
  authType: "oauth2" | "api_key" | "credentials" | "s3" | "none";
  docsUrl: string;
  featured?: boolean;
  recommended?: boolean;
  tags: string[];
  /** Supported data objects for this connector */
  objects: ConnectorObjectDef[];
}

export const ALL_CONNECTORS: ConnectorDef[] = [
  // ── Ecommerce ────────────────────────────────────────────────
  {
    id: "c-shopify",
    name: "Shopify",
    slug: "shopify",
    category: "ecommerce",
    description: "Sync orders, products, customers, and inventory from your Shopify store in real-time.",
    color: "#96BF48",
    abbr: "SH",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 30 min",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/shopify",
    featured: true,
    recommended: true,
    tags: ["orders", "products", "inventory", "customers"],
    objects: [
      { id: "orders",    name: "Orders",    description: "Sales orders with line items and fulfilment",     rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "products",  name: "Products",  description: "Product catalogue including variants and images", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "customers", name: "Customers", description: "Customer profiles and purchase history",          rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "inventory", name: "Inventory", description: "Stock levels per location and variant",           rowCount: 0, syncMode: "full_refresh" },
      { id: "refunds",   name: "Refunds",   description: "Order refunds and adjustments",                  rowCount: 0, syncMode: "incremental" },
      { id: "discounts", name: "Discounts", description: "Discount codes and usage",                       rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-woocommerce",
    name: "WooCommerce",
    slug: "woocommerce",
    category: "ecommerce",
    description: "Pull orders, products, and customer data from WooCommerce WordPress stores.",
    color: "#7F54B3",
    abbr: "WC",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/woocommerce",
    recommended: true,
    tags: ["orders", "wordpress", "products"],
    objects: [
      { id: "orders",    name: "Orders",    description: "WooCommerce orders", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "products",  name: "Products",  description: "Product catalogue",  rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "customers", name: "Customers", description: "Customer accounts",  rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-magento",
    name: "Magento",
    slug: "magento",
    category: "ecommerce",
    description: "Enterprise ecommerce data including orders, catalog, customers, and quotes.",
    color: "#F26322",
    abbr: "MG",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/magento",
    tags: ["orders", "catalog", "enterprise"],
    objects: [
      { id: "orders",   name: "Orders",   description: "Sales orders", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "catalog",  name: "Catalog",  description: "Products and categories", rowCount: 0, syncMode: "full_refresh" },
      { id: "customers",name: "Customers",description: "Customer accounts", rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-amazon",
    name: "Amazon Seller Central",
    slug: "amazon",
    category: "ecommerce",
    description: "Sync Amazon marketplace data including orders, inventory, fees, and advertising.",
    color: "#FF9900",
    textColor: "#111",
    abbr: "AMZ",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/amazon",
    featured: true,
    tags: ["marketplace", "orders", "advertising"],
    objects: [
      { id: "orders",    name: "Orders",    description: "Marketplace orders", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "inventory", name: "Inventory", description: "FBA/FBM inventory",  rowCount: 0, syncMode: "full_refresh" },
      { id: "financials",name: "Financials",description: "Settlements and fees",rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-flipkart",
    name: "Flipkart",
    slug: "flipkart",
    category: "ecommerce",
    description: "Sync Flipkart Seller Hub data including orders, returns, payments, and listings.",
    color: "#F7791C",
    abbr: "FK",
    status: "beta",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/flipkart",
    tags: ["marketplace", "india", "orders"],
    objects: [
      { id: "orders",  name: "Orders",  description: "Flipkart orders",    rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "returns", name: "Returns", description: "Return requests",    rowCount: 0, syncMode: "incremental" },
      { id: "listings",name: "Listings",description: "Product listings",   rowCount: 0, syncMode: "full_refresh" },
    ],
  },

  // ── Payments ─────────────────────────────────────────────────
  {
    id: "c-stripe",
    name: "Stripe",
    slug: "stripe",
    category: "payments",
    description: "Complete payment data including charges, subscriptions, invoices, payouts, and disputes.",
    color: "#635BFF",
    abbr: "ST",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/stripe",
    featured: true,
    recommended: true,
    tags: ["payments", "subscriptions", "invoices"],
    objects: [
      { id: "charges",       name: "Charges",       description: "Payment charges",           rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "customers",     name: "Customers",     description: "Stripe customers",           rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "subscriptions", name: "Subscriptions", description: "Recurring subscriptions",   rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "invoices",      name: "Invoices",      description: "Invoices and line items",   rowCount: 0, syncMode: "incremental" },
      { id: "payouts",       name: "Payouts",       description: "Bank payouts",              rowCount: 0, syncMode: "incremental" },
      { id: "disputes",      name: "Disputes",      description: "Chargebacks and disputes",  rowCount: 0, syncMode: "incremental" },
      { id: "refunds",       name: "Refunds",       description: "Charge refunds",            rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-razorpay",
    name: "Razorpay",
    slug: "razorpay",
    category: "payments",
    description: "Sync Razorpay payments, orders, refunds, settlements, and subscription data.",
    color: "#3395FF",
    abbr: "RZ",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/razorpay",
    recommended: true,
    tags: ["payments", "india", "settlements"],
    objects: [
      { id: "payments",     name: "Payments",     description: "Payment transactions",       rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "orders",       name: "Orders",       description: "Razorpay orders",            rowCount: 0, syncMode: "incremental" },
      { id: "settlements",  name: "Settlements",  description: "Bank settlement reports",    rowCount: 0, syncMode: "incremental" },
      { id: "refunds",      name: "Refunds",      description: "Payment refunds",            rowCount: 0, syncMode: "incremental" },
      { id: "subscriptions",name: "Subscriptions",description: "Razorpay subscriptions",     rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-paypal",
    name: "PayPal",
    slug: "paypal",
    category: "payments",
    description: "Extract PayPal transactions, disputes, payouts, subscriptions, and invoices.",
    color: "#003087",
    abbr: "PP",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/paypal",
    tags: ["payments", "transactions", "invoices"],
    objects: [
      { id: "transactions", name: "Transactions", description: "PayPal transactions", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "invoices",     name: "Invoices",     description: "PayPal invoices",     rowCount: 0, syncMode: "incremental" },
      { id: "payouts",      name: "Payouts",      description: "Payout records",      rowCount: 0, syncMode: "incremental" },
    ],
  },

  // ── Marketing / Ads ──────────────────────────────────────────
  {
    id: "c-ga4",
    name: "Google Analytics 4",
    slug: "google_analytics",
    category: "analytics",
    description: "Pull GA4 events, conversions, audiences, user properties, and funnel data.",
    color: "#F9AB00",
    textColor: "#111",
    abbr: "GA",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/ga4",
    featured: true,
    recommended: true,
    tags: ["analytics", "events", "funnels"],
    objects: [
      { id: "events",       name: "Events",        description: "Raw GA4 event data",              rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "conversions",  name: "Conversions",   description: "Conversion events and goals",     rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "sessions",     name: "Sessions",      description: "Session-level aggregated data",   rowCount: 0, syncMode: "incremental" },
      { id: "users",        name: "Users",         description: "User properties and cohorts",     rowCount: 0, syncMode: "full_refresh" },
      { id: "page_views",   name: "Page Views",    description: "Page view events",                rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-google-ads",
    name: "Google Ads",
    slug: "google_ads",
    category: "marketing",
    description: "Sync campaigns, ad groups, keywords, bids, and performance metrics from Google Ads.",
    color: "#4285F4",
    abbr: "GG",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/google-ads",
    featured: true,
    recommended: true,
    tags: ["ads", "campaigns", "keywords", "ppc"],
    objects: [
      { id: "campaigns",   name: "Campaigns",   description: "Ad campaigns",           rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "ad_groups",   name: "Ad Groups",   description: "Ad groups and targeting",rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "keywords",    name: "Keywords",    description: "Keyword performance",     rowCount: 0, syncMode: "incremental" },
      { id: "ads",         name: "Ads",         description: "Individual ad creatives", rowCount: 0, syncMode: "incremental" },
      { id: "performance", name: "Performance", description: "Daily performance metrics",rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-meta-ads",
    name: "Meta Ads",
    slug: "facebook_ads",
    category: "marketing",
    description: "Facebook and Instagram ad campaigns, audiences, creatives, and attribution data.",
    color: "#1877F2",
    abbr: "FB",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/meta-ads",
    featured: true,
    tags: ["ads", "facebook", "instagram", "campaigns"],
    objects: [
      { id: "campaigns",   name: "Campaigns",   description: "Meta ad campaigns",       rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "ad_sets",     name: "Ad Sets",     description: "Audience and budget sets",rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "ads",         name: "Ads",         description: "Individual ad creatives", rowCount: 0, syncMode: "incremental" },
      { id: "insights",    name: "Insights",    description: "Performance metrics",     rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-tiktok-ads",
    name: "TikTok Ads",
    slug: "tiktok_ads",
    category: "marketing",
    description: "TikTok advertising data including campaigns, ad groups, creatives, and performance.",
    color: "#010101",
    abbr: "TK",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/tiktok-ads",
    recommended: true,
    tags: ["ads", "tiktok", "campaigns"],
    objects: [
      { id: "campaigns",name: "Campaigns",description: "TikTok campaigns",rowCount: 0,syncMode: "incremental",recommended: true },
      { id: "insights", name: "Insights", description: "Performance data", rowCount: 0,syncMode: "incremental" },
    ],
  },
  {
    id: "c-linkedin-ads",
    name: "LinkedIn Ads",
    slug: "linkedin_ads",
    category: "marketing",
    description: "LinkedIn Campaign Manager data including sponsored content, lead gen forms, and demographics.",
    color: "#0A66C2",
    abbr: "LI",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/linkedin-ads",
    tags: ["ads", "b2b", "campaigns", "linkedin"],
    objects: [
      { id: "campaigns",   name: "Campaigns",   description: "LinkedIn campaigns",      rowCount: 0,syncMode: "incremental",recommended: true },
      { id: "analytics",   name: "Analytics",   description: "Campaign analytics",      rowCount: 0,syncMode: "incremental" },
      { id: "lead_gen",    name: "Lead Gen",    description: "Lead gen form submissions",rowCount: 0,syncMode: "incremental" },
    ],
  },
  {
    id: "c-klaviyo",
    name: "Klaviyo",
    slug: "klaviyo",
    category: "marketing",
    description: "Email marketing flows, campaigns, segments, events, and subscriber metrics.",
    color: "#2BB573",
    abbr: "KL",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 3 hours",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/klaviyo",
    recommended: true,
    tags: ["email", "sms", "flows", "ecommerce"],
    objects: [
      { id: "profiles",  name: "Profiles",  description: "Subscriber profiles",  rowCount: 0,syncMode: "incremental",recommended: true },
      { id: "campaigns", name: "Campaigns", description: "Email campaigns",       rowCount: 0,syncMode: "incremental", recommended: true },
      { id: "events",    name: "Events",    description: "Email events",          rowCount: 0,syncMode: "incremental" },
      { id: "segments",  name: "Segments",  description: "Audience segments",     rowCount: 0,syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-mailchimp",
    name: "Mailchimp",
    slug: "mailchimp",
    category: "marketing",
    description: "Email campaigns, audiences, automations, reports, and subscriber activity.",
    color: "#FFE01B",
    textColor: "#241C15",
    abbr: "MC",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/mailchimp",
    tags: ["email", "campaigns", "lists"],
    objects: [
      { id: "campaigns", name: "Campaigns", description: "Email campaigns",rowCount: 0,syncMode: "incremental",recommended: true },
      { id: "members",   name: "Members",   description: "Audience members",rowCount: 0,syncMode: "incremental" },
    ],
  },

  // ── CRM ──────────────────────────────────────────────────────
  {
    id: "c-hubspot",
    name: "HubSpot",
    slug: "hubspot",
    category: "crm",
    description: "Contacts, companies, deals, tickets, marketing emails, and form submissions.",
    color: "#FF7A59",
    abbr: "HS",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/hubspot",
    featured: true,
    recommended: true,
    tags: ["crm", "contacts", "deals", "marketing"],
    objects: [
      { id: "contacts",  name: "Contacts",  description: "CRM contact records",            rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "companies", name: "Companies", description: "Company / account records",       rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "deals",     name: "Deals",     description: "Sales pipeline deals",            rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "tickets",   name: "Tickets",   description: "Support tickets",                 rowCount: 0, syncMode: "incremental" },
      { id: "emails",    name: "Emails",    description: "Marketing emails and campaigns",  rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-salesforce",
    name: "Salesforce",
    slug: "salesforce",
    category: "crm",
    description: "Full Salesforce CRM: accounts, contacts, leads, opportunities, cases, and custom objects.",
    color: "#00A1E0",
    abbr: "SF",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/salesforce",
    featured: true,
    recommended: true,
    tags: ["crm", "enterprise", "opportunities", "leads"],
    objects: [
      { id: "accounts",     name: "Accounts",     description: "Account records",                rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "contacts",     name: "Contacts",     description: "Contact records",                rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "leads",        name: "Leads",        description: "Lead records",                   rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "opportunities",name: "Opportunities",description: "Opportunity / deal records",     rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "cases",        name: "Cases",        description: "Support case records",           rowCount: 0, syncMode: "incremental" },
      { id: "tasks",        name: "Tasks",        description: "Activities and tasks",           rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-zoho-crm",
    name: "Zoho CRM",
    slug: "zoho_crm",
    category: "crm",
    description: "Leads, contacts, accounts, deals, and activities from Zoho CRM.",
    color: "#E42527",
    abbr: "ZO",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/zoho-crm",
    recommended: true,
    tags: ["crm", "leads", "deals"],
    objects: [
      { id: "leads",    name: "Leads",    description: "Lead records",          rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "contacts", name: "Contacts", description: "Contact records",       rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "accounts", name: "Accounts", description: "Account records",       rowCount: 0, syncMode: "incremental" },
      { id: "deals",    name: "Deals",    description: "Deal / opportunity records", rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-pipedrive",
    name: "Pipedrive",
    slug: "pipedrive",
    category: "crm",
    description: "Sales pipelines, deals, activities, contacts, and organizations from Pipedrive.",
    color: "#1F2D3D",
    abbr: "PD",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/pipedrive",
    tags: ["crm", "sales", "deals", "pipeline"],
    objects: [
      { id: "deals",         name: "Deals",         description: "Sales pipeline deals",      rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "contacts",      name: "Contacts",      description: "Person contact records",    rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "organizations", name: "Organizations", description: "Company records",           rowCount: 0, syncMode: "incremental" },
      { id: "activities",    name: "Activities",    description: "Calls, meetings, emails",   rowCount: 0, syncMode: "incremental" },
    ],
  },

  // ── Support ───────────────────────────────────────────────────
  {
    id: "c-zendesk",
    name: "Zendesk",
    slug: "zendesk",
    category: "support",
    description: "Support tickets, users, agents, organizations, satisfaction ratings, and macros.",
    color: "#03363D",
    abbr: "ZD",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/zendesk",
    recommended: true,
    tags: ["support", "tickets", "helpdesk"],
    objects: [
      { id: "tickets",       name: "Tickets",       description: "Support tickets",             rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "users",         name: "Users",         description: "End-users and customers",     rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "organizations", name: "Organizations", description: "Customer organizations",      rowCount: 0, syncMode: "incremental" },
      { id: "satisfaction_ratings", name: "Satisfaction Ratings", description: "CSAT survey responses", rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-freshdesk",
    name: "Freshdesk",
    slug: "freshdesk",
    category: "support",
    description: "Tickets, contacts, agents, groups, and CSAT data from Freshdesk.",
    color: "#25C16F",
    abbr: "FD",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/freshdesk",
    tags: ["support", "tickets", "helpdesk"],
    objects: [
      { id: "tickets",  name: "Tickets",  description: "Support tickets",         rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "contacts", name: "Contacts", description: "Customer contacts",       rowCount: 0, syncMode: "incremental" },
      { id: "agents",   name: "Agents",   description: "Support agent records",   rowCount: 0, syncMode: "full_refresh" },
    ],
  },

  // ── Databases ─────────────────────────────────────────────────
  {
    id: "c-postgresql",
    name: "PostgreSQL",
    slug: "postgresql",
    category: "database",
    description: "Real-time CDC or scheduled sync from any PostgreSQL database version 10+.",
    color: "#336791",
    abbr: "PG",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 15 min",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/postgresql",
    featured: true,
    recommended: true,
    tags: ["database", "sql", "cdc", "rds"],
    objects: [
      { id: "tables", name: "Tables", description: "Discovered tables (schema auto-detected at connect time)", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "Database views",                                          rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-mysql",
    name: "MySQL",
    slug: "mysql",
    category: "database",
    description: "Full table sync or CDC from MySQL and compatible databases (MariaDB, Aurora).",
    color: "#4479A1",
    abbr: "MY",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 30 min",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/mysql",
    recommended: true,
    tags: ["database", "sql", "cdc", "aurora"],
    objects: [
      { id: "tables", name: "Tables", description: "Discovered tables (schema auto-detected at connect time)", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "Database views",                                          rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-mongodb",
    name: "MongoDB",
    slug: "mongodb",
    category: "database",
    description: "Sync collections, documents, and change streams from MongoDB Atlas or self-hosted.",
    color: "#47A248",
    abbr: "MDB",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/mongodb",
    tags: ["database", "nosql", "documents"],
    objects: [
      { id: "collections", name: "Collections", description: "MongoDB collections (schema inferred at connect time)", rowCount: 0, syncMode: "incremental", recommended: true },
    ],
  },
  {
    id: "c-mssql",
    name: "SQL Server",
    slug: "sql_server",
    category: "database",
    description: "Microsoft SQL Server: tables, views, stored procedures, and CDC via log reading.",
    color: "#CC2927",
    abbr: "SQL",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 30 min",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/sql-server",
    tags: ["database", "sql", "microsoft", "cdc"],
    objects: [
      { id: "tables", name: "Tables", description: "Discovered SQL Server tables", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "SQL Server views",             rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-oracle",
    name: "Oracle DB",
    slug: "oracle",
    category: "database",
    description: "Oracle Database tables and views using JDBC or LogMiner for CDC replication.",
    color: "#F80000",
    abbr: "ORC",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/oracle",
    tags: ["database", "enterprise", "sql", "jdbc"],
    objects: [
      { id: "tables", name: "Tables", description: "Oracle DB tables (schema auto-detected)", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "Oracle views",                            rowCount: 0, syncMode: "full_refresh" },
    ],
  },

  // ── Warehouses ────────────────────────────────────────────────
  {
    id: "c-snowflake",
    name: "Snowflake",
    slug: "snowflake",
    category: "warehouse",
    description: "Query Snowflake tables and views as a data source or use as a sync destination.",
    color: "#29B5E8",
    abbr: "SF",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Daily",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/snowflake",
    featured: true,
    tags: ["warehouse", "cloud", "sql"],
    objects: [
      { id: "tables", name: "Tables", description: "Snowflake tables across schemas", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "Snowflake views",                 rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-bigquery",
    name: "BigQuery",
    slug: "bigquery",
    category: "warehouse",
    description: "Google BigQuery tables, views, and external tables as source or destination.",
    color: "#4285F4",
    abbr: "BQ",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/bigquery",
    featured: true,
    recommended: true,
    tags: ["warehouse", "google", "sql"],
    objects: [
      { id: "tables", name: "Tables", description: "BigQuery tables across datasets", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "BigQuery views",                  rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-redshift",
    name: "Amazon Redshift",
    slug: "redshift",
    category: "warehouse",
    description: "AWS Redshift tables as source or destination with high-throughput COPY commands.",
    color: "#8C4FFF",
    abbr: "RS",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/redshift",
    tags: ["warehouse", "aws", "sql"],
    objects: [
      { id: "tables", name: "Tables", description: "Redshift tables across schemas", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "views",  name: "Views",  description: "Redshift views",                 rowCount: 0, syncMode: "full_refresh" },
    ],
  },

  // ── Storage ───────────────────────────────────────────────────
  {
    id: "c-s3",
    name: "Amazon S3",
    slug: "s3",
    category: "storage",
    description: "Read CSV, JSON, Parquet, and Avro files from S3 buckets with auto schema detection.",
    color: "#FF9900",
    textColor: "#111",
    abbr: "S3",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "s3",
    docsUrl: "https://docs.crosstecch.io/connectors/s3",
    recommended: true,
    tags: ["storage", "aws", "files", "parquet"],
    objects: [
      { id: "files", name: "Files", description: "CSV, JSON, Parquet, or Avro files in S3 buckets (path pattern configured at connect time)", rowCount: 0, syncMode: "full_refresh", recommended: true },
    ],
  },
  {
    id: "c-azure-blob",
    name: "Azure Blob Storage",
    slug: "azure_blob",
    category: "storage",
    description: "Read files from Azure Blob Storage and Data Lake Storage Gen2.",
    color: "#0078D4",
    abbr: "AZ",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 6 hours",
    totalRecords: 0,
    authType: "credentials",
    docsUrl: "https://docs.crosstecch.io/connectors/azure-blob",
    tags: ["storage", "azure", "files"],
    objects: [
      { id: "files", name: "Files", description: "Files in Azure Blob containers (path pattern configured at connect time)", rowCount: 0, syncMode: "full_refresh", recommended: true },
    ],
  },
  {
    id: "c-google-sheets",
    name: "Google Sheets",
    slug: "google_sheets",
    category: "productivity",
    description: "Sync spreadsheet data from Google Sheets with auto column detection and type inference.",
    color: "#34A853",
    abbr: "GS",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 15 min",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/google-sheets",
    recommended: true,
    tags: ["spreadsheet", "google", "files"],
    objects: [
      { id: "sheets", name: "Sheets", description: "Individual sheets within a Google Sheets document", rowCount: 0, syncMode: "full_refresh", recommended: true },
    ],
  },
  {
    id: "c-excel",
    name: "Microsoft Excel",
    slug: "excel",
    category: "productivity",
    description: "Import Excel files (.xlsx, .xls) from OneDrive, SharePoint, or local upload.",
    color: "#217346",
    abbr: "XL",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Manual",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/excel",
    tags: ["spreadsheet", "microsoft", "files"],
    objects: [
      { id: "worksheets", name: "Worksheets", description: "Individual worksheets within an Excel workbook", rowCount: 0, syncMode: "full_refresh", recommended: true },
    ],
  },
  {
    id: "c-csv",
    name: "CSV / File Upload",
    slug: "csv",
    category: "storage",
    description: "Upload CSV, TSV, or JSON files directly with column mapping and type detection.",
    color: "#6B7280",
    abbr: "CSV",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Manual",
    totalRecords: 0,
    authType: "none",
    docsUrl: "https://docs.crosstecch.io/connectors/csv",
    recommended: true,
    tags: ["files", "csv", "upload"],
    objects: [
      { id: "uploaded_file", name: "Uploaded File", description: "Rows from the uploaded CSV, TSV, or JSON file", rowCount: 0, syncMode: "full_refresh", recommended: true },
    ],
  },

  // ── Productivity / Collaboration ──────────────────────────────
  {
    id: "c-slack",
    name: "Slack",
    slug: "slack",
    category: "productivity",
    description: "Export Slack messages, channels, users, reactions, and file metadata.",
    color: "#4A154B",
    abbr: "SL",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/slack",
    tags: ["collaboration", "messaging", "channels"],
    objects: [
      { id: "messages", name: "Messages", description: "Channel messages and threads", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "channels", name: "Channels", description: "Channel metadata",            rowCount: 0, syncMode: "full_refresh" },
      { id: "users",    name: "Users",    description: "Workspace member profiles",   rowCount: 0, syncMode: "full_refresh" },
    ],
  },
  {
    id: "c-notion",
    name: "Notion",
    slug: "notion",
    category: "productivity",
    description: "Sync Notion databases, pages, and blocks including properties and relations.",
    color: "#191919",
    abbr: "NT",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 2 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/notion",
    tags: ["wiki", "databases", "pages"],
    objects: [
      { id: "databases", name: "Databases", description: "Notion database records",     rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "pages",     name: "Pages",     description: "Notion pages and sub-pages", rowCount: 0, syncMode: "incremental" },
    ],
  },

  // ── Dev Tools ─────────────────────────────────────────────────
  {
    id: "c-jira",
    name: "Jira",
    slug: "jira",
    category: "devtools",
    description: "Issues, sprints, projects, epics, and velocity metrics from Jira Cloud or Server.",
    color: "#0052CC",
    abbr: "JR",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/jira",
    recommended: true,
    tags: ["project management", "issues", "sprints"],
    objects: [
      { id: "issues",   name: "Issues",   description: "Jira issues and sub-tasks",  rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "projects", name: "Projects", description: "Project metadata",            rowCount: 0, syncMode: "full_refresh" },
      { id: "sprints",  name: "Sprints",  description: "Sprint and velocity data",   rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-github",
    name: "GitHub",
    slug: "github",
    category: "devtools",
    description: "Repositories, issues, pull requests, commits, actions runs, and deployments.",
    color: "#24292E",
    abbr: "GH",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 3 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/github",
    tags: ["git", "repos", "prs", "issues"],
    objects: [
      { id: "issues",       name: "Issues",        description: "GitHub issues",           rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "pull_requests",name: "Pull Requests", description: "PRs and review activity", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "repositories", name: "Repositories",  description: "Repo metadata",           rowCount: 0, syncMode: "full_refresh" },
      { id: "commits",      name: "Commits",       description: "Commit history",          rowCount: 0, syncMode: "incremental" },
    ],
  },
  {
    id: "c-gitlab",
    name: "GitLab",
    slug: "gitlab",
    category: "devtools",
    description: "Projects, merge requests, pipelines, issues, and CI/CD metrics from GitLab.",
    color: "#FC6D26",
    abbr: "GL",
    status: "beta",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every 3 hours",
    totalRecords: 0,
    authType: "oauth2",
    docsUrl: "https://docs.crosstecch.io/connectors/gitlab",
    tags: ["git", "ci/cd", "pipelines", "devops"],
    objects: [
      { id: "merge_requests", name: "Merge Requests", description: "GitLab MRs and reviews", rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "issues",         name: "Issues",         description: "GitLab issues",           rowCount: 0, syncMode: "incremental" },
      { id: "pipelines",      name: "Pipelines",      description: "CI/CD pipeline runs",     rowCount: 0, syncMode: "incremental" },
    ],
  },

  // ── Analytics ─────────────────────────────────────────────────
  {
    id: "c-mixpanel",
    name: "Mixpanel",
    slug: "mixpanel",
    category: "analytics",
    description: "Export raw events, user profiles, funnels, and cohort data from Mixpanel.",
    color: "#7856FF",
    abbr: "MX",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Daily",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/mixpanel",
    recommended: true,
    tags: ["analytics", "events", "funnels", "cohorts"],
    objects: [
      { id: "events",   name: "Events",   description: "Raw event stream",           rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "profiles", name: "Profiles", description: "User profile properties",    rowCount: 0, syncMode: "incremental", recommended: true },
      { id: "funnels",  name: "Funnels",  description: "Funnel analysis results",    rowCount: 0, syncMode: "full_refresh" },
      { id: "cohorts",  name: "Cohorts",  description: "Audience cohort definitions",rowCount: 0, syncMode: "full_refresh" },
    ],
  },

  // ── Outreach ──────────────────────────────────────────────────
  {
    id: "c-instantly",
    name: "Instantly",
    slug: "instantly",
    category: "marketing",
    description: "Cold email outreach campaigns, lead lists, inbox warmup, and reply tracking from Instantly.ai.",
    color: "#FF6B35",
    abbr: "IN",
    status: "available",
    health: null,
    lastSync: null,
    nextSync: null,
    syncFrequency: "Every hour",
    totalRecords: 0,
    authType: "api_key",
    docsUrl: "https://docs.crosstecch.io/connectors/instantly",
    featured: true,
    recommended: true,
    tags: ["email", "outreach", "campaigns", "leads", "warmup"],
    objects: [
      { id: "campaigns", name: "Campaigns", description: "Email outreach campaigns with stats",        rowCount: 0, syncMode: "full_refresh",  recommended: true },
      { id: "leads",     name: "Leads",     description: "Prospect contacts in campaigns",             rowCount: 0, syncMode: "incremental",   recommended: true },
      { id: "replies",   name: "Replies",   description: "Email replies with sentiment analysis",      rowCount: 0, syncMode: "incremental",   recommended: true },
      { id: "events",    name: "Events",    description: "Open, click, bounce, and unsubscribe events",rowCount: 0, syncMode: "incremental" },
      { id: "inboxes",   name: "Inboxes",   description: "Sending inbox accounts and warmup status",   rowCount: 0, syncMode: "full_refresh" },
    ],
  },
];

export const CATEGORY_LABELS: Record<ConnectorCategory, string> = {
  ecommerce: "E-Commerce",
  payments: "Payments",
  marketing: "Marketing",
  crm: "CRM",
  support: "Support",
  database: "Databases",
  warehouse: "Warehouses",
  storage: "Storage",
  productivity: "Productivity",
  devtools: "Dev Tools",
  analytics: "Analytics",
};

export const CATEGORY_COLORS: Record<ConnectorCategory, string> = {
  ecommerce: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400",
  payments: "bg-violet-50 text-violet-700 dark:bg-violet-950/30 dark:text-violet-400",
  marketing: "bg-orange-50 text-orange-700 dark:bg-orange-950/30 dark:text-orange-400",
  crm: "bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-400",
  support: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/30 dark:text-cyan-400",
  database: "bg-slate-50 text-slate-700 dark:bg-slate-950/30 dark:text-slate-400",
  warehouse: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/30 dark:text-indigo-400",
  storage: "bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400",
  productivity: "bg-pink-50 text-pink-700 dark:bg-pink-950/30 dark:text-pink-400",
  devtools: "bg-gray-50 text-gray-700 dark:bg-gray-950/30 dark:text-gray-400",
  analytics: "bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-400",
};
